name: portfolio_app
description: A new Flutter portfolio app

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10  # <- make sure this line is correctly indented


flutter_icons:
  android: true
  ios: true
  image_path: "assets/image.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/profile.jpg
